### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by beqabeqa473** [Aculeasis/rhvoice-rest#1]
hello.

i have some suggestions to improve api.

1. is it possible to implement rate,pitch,volume to pass as parameters as it is now for text,voice,format?
2. use supported voices from library itself and remove hardcoded list of voices in app.py.
3. implement cashing support where filename will be based on entered params in md5.

thanks

**Comment by Aculeasis** [comment]
Hello.
1. I implement this, after implement in rhvoice-wrapper. Not all options, only absolute rate, pitch, volume?
2. This is already that. `SUPPORT_VOICES` and `FORMATS` rewrite before server starting.
3. May be as option. I think is bad idea. RHVoice fast enough for work without cache.

Thanks!

**Comment by beqabeqa473** [comment]
maybe then remove this list of hardcoded voices?

2018-10-11 17:35 GMT+04:00, Aculeasis <notifications@github.com>:
> Hello.
> 1. I implement this, after implement in rhvoice-wrapper. Not all options,
> only absolute rate, pitch, volume?
> 2. This is already that. `SUPPORT_VOICES` and `FORMATS` rewrite before
> server starting.
> 3. May be as option. I think is bad idea. RHVoice fast enough for work
> without cache.
>
> Thanks!
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Aculeasis/rhvoice-rest/issues/1#issuecomment-428957578


-- 
with best regards beqa

**Comment by beqabeqa473** [comment]
hi.
and last comment in this thread i think:
is it possible to implement cache lifetime and periodic check interval if cache file should be deleted?

thanks.

**Comment by Aculeasis** [comment]
Also, `os.path.getatime` return last access time only if fs mount without `noatime`. Else this return creation time.
I have no systems without `noatime`.
