### ISSUE TITLE
Rhasspy Remote TTS

### ISSUE THREAD

**Issue by Omirax** [Aculeasis/rhvoice-rest#5]
Здравствуйте!

Спасибо за Вашу отличную работу!
Пожалуй, это лучший TTS! 

Нет ли в планах интеграции в Rhasspy в качестве модуля TTS или сделать адаптацию для Remote TTS?

Спасибо!

**Comment by Aculeasis** [comment]
Для адаптации к Remote TTS нужно узнать что он в запросе передает, я не нашел этого в доках.

Там есть command, через него можно вызывать сам [RHVoice](https://github.com/RHVoice/RHVoice) или написать скрипт-прослойку.

Если используется HA, то можно в него интегрировать https://github.com/definitio/ha-rhvoice

**Comment by Aculeasis** [comment]
Добавил поддержку, вроде работает. Воспроизведение не проверял, нет аудиосистемы на сервере.

Если у вас докер, то нужно подождать пока он пересоберется https://hub.docker.com/repository/docker/aculeasis/rhvoice-rest

**Comment by Omirax** [comment]
ЗдОрово!

Да, докер, конечно. 
И Вашей интеграцией пользуюсь ну уже очень давно (как и все, кому я ставил УД). Это лучшее, что есть оффлайн в HA.

Новую версию проверил, все работает! 
Это просто отлично!

Есть маленький нюанс, что хорошо бы было еще параметры output wav можно было задавать.  Ибо стерео зачастую это лишнее как и samplerate > 16000 ну в крайнем случае 21050. Так как я, к примеру, использую Rhasspy Satellite на основе ESP32 и там хватает своих заморочек.

Еще раз огромное спасибо!

**Comment by Aculeasis** [comment]
Модели на 16000 я выкинул для уменьшения размера. А стерео тут нет:
```
mediainfo hello.wav 
General
Complete name                            : hello.wav
Format                                   : Wave
File size                                : 26.8 KiB
Duration                                 : 570 ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 385 kb/s
IsTruncated                              : Yes

Audio
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 1
Duration                                 : 570 ms
Bit rate mode                            : Constant
Bit rate                                 : 384 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 24.0 kHz
Bit depth                                : 16 bits
Stream size                              : 26.7 KiB (100%)

```

**Comment by Omirax** [comment]
Я уже так понял, как начал проводить тесты.
В принципе все отлично!
Еще раз спасибо!
